<?php
include("config/DB_Config.php");

try {
    // 1. Find all doctors in the 'users' table who do NOT have a profile yet
    $stmt = $conn->query("
        SELECT * FROM users 
        WHERE role = 'doctor' 
        AND \"userID\" NOT IN (SELECT \"userID\" FROM \"doctorProfile\")
    ");
    $missingProfileDocs = $stmt->fetchAll(PDO::FETCH_ASSOC);

    if (empty($missingProfileDocs)) {
        echo "All doctors already have a profile!\n";
    } else {
        // 2. Insert a default profile for each
        $insertQuery = "INSERT INTO \"doctorProfile\" (\"userID\", full_name, specialization, phone_number, description) 
                        VALUES (?, ?, ?, ?, ?)";
        $insertStmt = $conn->prepare($insertQuery);

        foreach ($missingProfileDocs as $doc) {
            $formattedName = "Dr. " . ucwords(str_replace('_', ' ', $doc['username']));
            $insertStmt->execute([
                $doc['userID'],
                $formattedName,
                'General Physician', // Default Spec
                '000-000-0000',      // Default Phone
                'Autogenerated Profile'
            ]);
            echo "Created profile for user: " . $doc['username'] . " (ID: " . $doc['userID'] . ")\n";
        }
        echo "Successfully created missing doctor profiles.\n";
    }
} catch (Exception $e) {
    echo "Error: " . $e->getMessage();
}
